name: Python Selenium Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
           pip install driver 
           pip install --upgrade pip
           pip install -r requirements.txt
      - name: Run tests
        run: |
          python -m unittest discover -v -s . -p "test_*.py"
      - name: Check for test failures
        if: ${{ job.status == 'success' && steps.test.outcome == 'failure' }}
        run: exit 1

